config/routes.rb
Rails.application.routes.draw do
  resources :personas, except: [:show, :new]
  resources :proyectos, except: [:show, :new]
  

  delete 'asignacions/:persona_id/:proyecto_id', to: 'asignacions#destroy', as: 'asignacion_del'
  post 'asignacions/:persona_id', to: 'asignacions#create', as:'asignacions'
  
  root 'personas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asignacion.rb
class Asignacion < ApplicationRecord
  belongs_to :persona
  belongs_to :proyecto

  validates :persona_id, uniqueness: { scope: :proyecto_id,
    message: "El proyecto ya fue asignado a esta persona" }
end

app/models/persona.rb
class Persona < ApplicationRecord
	has_many :asignacions
	has_many :proyectos, through: :asignacions
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
	has_many :asignacions
	has_many :personas, through: :asignacions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/asignacions_controller.rb
class AsignacionsController < ApplicationController
	before_action :set_asignacion, only: [:show, :edit, :update, :destroy]

	def create
		@asignacion = Asignacion.new
		@asignacion.persona_id = params[:persona_id]
		@asignacion.proyecto_id = params[:proyecto_id]
		@asignacion.save
		redirect_to root_path
	end


	def destroy
		@asignacion.destroy
    	redirect_to root_path, notice: 'Asignación was successfully destroyed.'

	end


	private

	def set_asignacion
		@asignacion = Asignacion.where(persona_id: params[:persona_id],proyecto_id: params[:proyecto_id]).first
		
	end


end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
before_action :set_persona, only: [:show, :edit, :update, :destroy]

  def index
  	@personas = Persona.all
    @persona = Persona.new
  end

	def create
		@persona = Persona.new(persona_params)
		@persona.save
		redirect_to root_path

	#	respond_to do |format|
     # if @product.save

        #format.html { redirect_to @persona, notice: 'Persona fue creada' }
        #format.json { render :show, status: :created, location: @persona }
      #else
       # format.html { render :new }
       # format.json { render json: @product.errors, status: :unprocessable_entity }
      #end
	end 


  def edit
  end

  def update
    @persona.update(persona_params)
    redirect_to root_path, notice: 'Persona was successfully updated.'
  end


  def destroy
    @persona.destroy
    redirect_to root_path, notice: 'Persona was successfully destroyed.'
  end

	private

  def set_persona
      @persona = Persona.find(params[:id])
  end

	def persona_params
      params.require(:persona).permit(:name)
  end

end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
	before_action :set_proyecto, only: [:show, :edit, :update, :destroy]

 	def index
  		@proyectos = Proyecto.all
    	@proyecto = Proyecto.new
 	end

 	def create
		@proyecto = Proyecto.new(proyecto_params)
		@proyecto.save
		redirect_to proyectos_path
	end

	def edit
 	end

	def update
	    @proyecto.update(proyecto_params)
	    redirect_to proyectos_path, notice: 'Proyecto was successfully updated.'
	end


	def destroy
	    @proyecto.destroy
	    redirect_to proyectos_path, notice: 'Proyecto was successfully destroyed.'
	end


	private
	
	def set_proyecto
      @proyecto = Proyecto.find(params[:id])
 	end

	def proyecto_params
      params.require(:proyecto).permit(:nombre)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asignacions_helper.rb
module AsignacionsHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Personal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <ul class="nav bg-light">
      <li class="nav-item">
        <%= link_to 'Personas', personas_path, :class => 'nav-link text-dark' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Proyectos', proyectos_path, :class => 'nav-link text-dark' %>
      </li>
    </ul>
    
    <p class="alert"><%= alert %></p>
    <p class="notice"><%= notice %></p>



    <%= yield %>
  </body>
</html>

app/views/personas/edit.html.erb
<h3>Editar Persona</h3>

<%= form_with(model: @persona, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/personas/index.html.erb
<h1>Personas</h1>

<table class="table">
	<thead> 
		<td>Nombre</td>
		<td>Proyectos asociados</td>
		<td>Asignar Proyectos</td>
	</thead>
	<% @personas.each do |persona| %>
		<tr>
			<td><%= link_to 'Eliminar', persona_path(persona), method: :delete, :class => 'btn btn-sm btn-danger' %>
				<%= link_to 'Editar', edit_persona_path(persona), :class => 'btn btn-sm btn-success' %>
				<%= persona.name %>
			</td>
			<td>
				<% persona.proyectos.each do |proyecto| %>
					<%= proyecto.nombre %>
					<%= link_to 'Borrar', asignacion_del_path(persona, proyecto), method: :delete %>
					|
				<% end %>
			</td>
			<td>
				<%= form_with(model: @asignacion, url: asignacions_path(persona), local: true) do |f| %>

					<%= f.select :proyecto_id, Proyecto.pluck(:nombre, :id) %>

					<%= f.submit "Agregar", :class => 'btn btn-sm btn-light' %>
				<% end %>


			</td>
		</tr>
	<% end %>

</table>
<br>
<h3>Agregar Persona</h3>

<%= form_with(model: @persona, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proyectos/edit.html.erb
<h3>Editar Proyecto</h3>

<%= form_with(model: @proyecto, local: true) do |form| %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proyectos/index.html.erb
<h1>Proyectos</h1>

<table class="table">
	<thead> 
		<td>Nombre</td>
		<td>Personas asociados</td>
	</thead>
	<% @proyectos.each do |proyecto| %>
		<tr>
			<td><%= link_to 'Eliminar', proyecto_path(proyecto), method: :delete, :class => 'btn btn-sm btn-danger' %>
				<%= link_to 'Editar', edit_proyecto_path(proyecto), :class => 'btn btn-sm btn-success' %>
				<%= proyecto.nombre %>
			</td>
			<td>
				<% proyecto.personas.each do |persona| %>
					<%= persona.name %>
					|
				<% end %>
			</td>
			
		</tr>
	<% end %>

</table>
<br>
<h3>Agregar Proyecto</h3>

<%= form_with(model: @proyecto, local: true) do |form| %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>